//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;
using System.Diagnostics;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Xml.Schema;

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 

namespace ImageBoardProcessor.Models
{

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false,DataType ="string",ElementName="posts")]
    public partial class Rule34Model
    {

        private Image[] postField;

        private string countField;

        private string offsetField;

        /// <remarks/>
        [XmlElementAttribute("post", Form = XmlSchemaForm.Unqualified)]
        public Image[] post
        {
            get
            {
                return this.postField;
            }
            set
            {
                this.postField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true,IncludeInSchema = true, Namespace ="",TypeName ="post")]
    public partial class Image
    {

        private string heightField;

        private string scoreField;

        private string file_urlField;

        private string parent_idField;

        private string sample_urlField;

        private string sample_widthField;

        private string sample_heightField;

        private string preview_urlField;

        private string ratingField;

        private string tagsField;

        private string idField;

        private string widthField;

        private string changeField;

        private string md5Field;

        private string creator_idField;

        private string has_childrenField;

        private string created_atField;

        private string statusField;

        private string sourceField;

        private string has_notesField;

        private string has_commentsField;

        private string preview_widthField;

        private string preview_heightField;

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string file_url
        {
            get
            {
                return this.file_urlField;
            }
            set
            {
                this.file_urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string parent_id
        {
            get
            {
                return this.parent_idField;
            }
            set
            {
                this.parent_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string sample_url
        {
            get
            {
                return this.sample_urlField;
            }
            set
            {
                this.sample_urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string sample_width
        {
            get
            {
                return this.sample_widthField;
            }
            set
            {
                this.sample_widthField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string sample_height
        {
            get
            {
                return this.sample_heightField;
            }
            set
            {
                this.sample_heightField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string preview_url
        {
            get
            {
                return this.preview_urlField;
            }
            set
            {
                this.preview_urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string rating
        {
            get
            {
                return this.ratingField;
            }
            set
            {
                this.ratingField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string tags
        {
            get
            {
                return this.tagsField;
            }
            set
            {
                this.tagsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string change
        {
            get
            {
                return this.changeField;
            }
            set
            {
                this.changeField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string md5
        {
            get
            {
                return this.md5Field;
            }
            set
            {
                this.md5Field = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string creator_id
        {
            get
            {
                return this.creator_idField;
            }
            set
            {
                this.creator_idField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string has_children
        {
            get
            {
                return this.has_childrenField;
            }
            set
            {
                this.has_childrenField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string created_at
        {
            get
            {
                return this.created_atField;
            }
            set
            {
                this.created_atField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string has_notes
        {
            get
            {
                return this.has_notesField;
            }
            set
            {
                this.has_notesField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string has_comments
        {
            get
            {
                return this.has_commentsField;
            }
            set
            {
                this.has_commentsField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string preview_width
        {
            get
            {
                return this.preview_widthField;
            }
            set
            {
                this.preview_widthField = value;
            }
        }

        /// <remarks/>
        [XmlAttributeAttribute()]
        public string preview_height
        {
            get
            {
                return this.preview_heightField;
            }
            set
            {
                this.preview_heightField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [SerializableAttribute()]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private Rule34Model[] itemsField;

        /// <remarks/>
        [XmlElementAttribute("posts")]
        public Rule34Model[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

}